### ISSUE TITLE
new index.js changes throw syntax errors

### ISSUE THREAD

**Issue by MrMcShroom** [Eric-Gurt/StarDefenders2D#86]
(node:14621) ExperimentalWarning: The ESM module loader is experimental.
file:///home/discordbots/html/index.js:3261
	worker_services.push( await RunWorkerService( 'Worker #'+i ) );
	                      ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
    at async link (internal/modules/esm/module_job.js:37:21)
Running vanilla game on this.

**Comment by Eric-Gurt** [comment]
Looks like it is fixed.
